title: "Essien's Excellence Academy"
description: "Official Website of Essien's Excellence Academy"
theme: minima

author: "Freeman"
 
  # Navigation links
header_pages:
  - about.md
  - academics.md
  - admissions.md
  - student-life.md
  - contact.md
  - parents.md
  - students.md
  - staff.md
