title: "Essien's Excellence Academy"
description: "Official Website of Essien's Excellence Academy"
theme: minima

permalink: pretty

# Add custom stylesheet
sass:
  style: compressed

include:
  - assets/css
author: "Freeman"
 
  # Navigation links
header_pages:
  - index.md
  - about.md
  - academics.md
  - admissions.md
  - student-life.md
  - contact.md
  - parents.md
  - students.md
  - staff.md
